"""Sports pipeline configuration — sport definitions, team aliases, constants."""

import re
from dataclasses import dataclass, field

# Reuse root-level API constants
from config import (
    CLOB_BASE_URL,
    CLOB_PAGE_LIMIT,
    GAMMA_BASE_URL,
    GAMMA_PAGE_LIMIT,
    GOLDSKY_EARLIEST_TIMESTAMP,
    GOLDSKY_PAGE_SIZE,
    GOLDSKY_SEMAPHORE,
    GOLDSKY_URL,
    POLYMARKET_SEMAPHORE,
    USDC_ASSET_ID,
)

# --- Sports-specific constants ---
ODDS_API_BASE = "https://api.the-odds-api.com/v4"
SPORTS_PRICE_FIDELITY = 15  # minutes
SPORTS_DB_PATH = "sports_data.db"
SPORTS_PRICE_LOOKBACK_DAYS = 7
ODDS_CREDITS_PER_CALL = 10
ODDS_CREDIT_BUDGET = 5_000_000
ODDS_RATE_LIMIT_DELAY = 0.01  # seconds between Odds API calls
SPORTS_GOLDSKY_SEMAPHORE = 8   # Workers for Goldsky queue (rate capped by token-bucket)
GOLDSKY_RATE_LIMIT = 45        # Max requests per window (Goldsky limit: 50/10s)
GOLDSKY_RATE_WINDOW = 10.0     # Rate limit window in seconds
GOLDSKY_RATE_BURST = 5         # Max burst tokens


@dataclass(frozen=True)
class SportConfig:
    name: str
    polymarket_tags: list[str] = field(default_factory=list)
    odds_api_sport_keys: list[str] = field(default_factory=list)
    gamma_series_ids: list[int] = field(default_factory=list)


SPORTS = {
    "NBA": SportConfig(
        name="NBA",
        polymarket_tags=["nba"],
        odds_api_sport_keys=["basketball_nba"],
        gamma_series_ids=[10345],
    ),
    "NFL": SportConfig(
        name="NFL",
        polymarket_tags=["nfl"],
        odds_api_sport_keys=["americanfootball_nfl"],
        gamma_series_ids=[10187],
    ),
    "NHL": SportConfig(
        name="NHL",
        polymarket_tags=["nhl"],
        odds_api_sport_keys=["icehockey_nhl"],
        gamma_series_ids=[10346],
    ),
    "MLB": SportConfig(
        name="MLB",
        polymarket_tags=["mlb"],
        odds_api_sport_keys=["baseball_mlb"],
        gamma_series_ids=[3],
    ),
    "Tennis": SportConfig(
        name="Tennis",
        polymarket_tags=["tennis"],
        odds_api_sport_keys=[
            "tennis_atp_aus_open_singles", "tennis_atp_french_open",
            "tennis_atp_wimbledon", "tennis_atp_us_open",
            "tennis_atp_indian_wells", "tennis_atp_miami_open",
            "tennis_atp_italian_open", "tennis_atp_canadian_open",
            "tennis_atp_cincinnati_open", "tennis_atp_shanghai_masters",
            "tennis_wta_aus_open_singles", "tennis_wta_french_open",
            "tennis_wta_wimbledon", "tennis_wta_us_open",
            "tennis_wta_indian_wells", "tennis_wta_miami_open",
            "tennis_wta_italian_open", "tennis_wta_canadian_open",
            "tennis_wta_cincinnati_open",
        ],
        gamma_series_ids=[10365, 10366],
    ),
    "Soccer": SportConfig(
        name="Soccer",
        polymarket_tags=[
            "soccer", "football", "epl", "premier-league",
            "champions-league", "la-liga", "mls",
        ],
        odds_api_sport_keys=[
            "soccer_epl",
            "soccer_usa_mls",
            "soccer_spain_la_liga",
            "soccer_italy_serie_a",
            "soccer_germany_bundesliga",
            "soccer_france_ligue_one",
            "soccer_uefa_champs_league",
        ],
        gamma_series_ids=[10188, 10193, 10189, 10203, 10194, 10195, 10204],
    ),
}

# --- Team alias dictionaries ---
# Maps short/common names -> canonical full name used for fuzzy matching.

NBA_ALIASES = {
    "celtics": "Boston Celtics",
    "boston": "Boston Celtics",
    "nets": "Brooklyn Nets",
    "brooklyn": "Brooklyn Nets",
    "knicks": "New York Knicks",
    "new york knicks": "New York Knicks",
    "76ers": "Philadelphia 76ers",
    "sixers": "Philadelphia 76ers",
    "philadelphia": "Philadelphia 76ers",
    "raptors": "Toronto Raptors",
    "toronto": "Toronto Raptors",
    "bulls": "Chicago Bulls",
    "chicago": "Chicago Bulls",
    "cavaliers": "Cleveland Cavaliers",
    "cavs": "Cleveland Cavaliers",
    "cleveland": "Cleveland Cavaliers",
    "pistons": "Detroit Pistons",
    "pistions": "Detroit Pistons",
    "detroit": "Detroit Pistons",
    "pacers": "Indiana Pacers",
    "indiana": "Indiana Pacers",
    "bucks": "Milwaukee Bucks",
    "milwaukee": "Milwaukee Bucks",
    "hawks": "Atlanta Hawks",
    "atlanta": "Atlanta Hawks",
    "hornets": "Charlotte Hornets",
    "charlotte": "Charlotte Hornets",
    "heat": "Miami Heat",
    "miami": "Miami Heat",
    "magic": "Orlando Magic",
    "orlando": "Orlando Magic",
    "wizards": "Washington Wizards",
    "washington": "Washington Wizards",
    "nuggets": "Denver Nuggets",
    "denver": "Denver Nuggets",
    "timberwolves": "Minnesota Timberwolves",
    "twolves": "Minnesota Timberwolves",
    "wolves": "Minnesota Timberwolves",
    "minnesota": "Minnesota Timberwolves",
    "thunder": "Oklahoma City Thunder",
    "okc": "Oklahoma City Thunder",
    "oklahoma city": "Oklahoma City Thunder",
    "trail blazers": "Portland Trail Blazers",
    "blazers": "Portland Trail Blazers",
    "portland": "Portland Trail Blazers",
    "jazz": "Utah Jazz",
    "utah": "Utah Jazz",
    "warriors": "Golden State Warriors",
    "golden state": "Golden State Warriors",
    "clippers": "Los Angeles Clippers",
    "la clippers": "Los Angeles Clippers",
    "lakers": "Los Angeles Lakers",
    "la lakers": "Los Angeles Lakers",
    "suns": "Phoenix Suns",
    "phoenix": "Phoenix Suns",
    "kings": "Sacramento Kings",
    "sacramento": "Sacramento Kings",
    "spurs": "San Antonio Spurs",
    "san antonio": "San Antonio Spurs",
    "mavericks": "Dallas Mavericks",
    "mavs": "Dallas Mavericks",
    "dallas": "Dallas Mavericks",
    "rockets": "Houston Rockets",
    "houston": "Houston Rockets",
    "grizzlies": "Memphis Grizzlies",
    "memphis": "Memphis Grizzlies",
    "pelicans": "New Orleans Pelicans",
    "new orleans": "New Orleans Pelicans",
}

NFL_ALIASES = {
    "cardinals": "Arizona Cardinals",
    "arizona": "Arizona Cardinals",
    "falcons": "Atlanta Falcons",
    "ravens": "Baltimore Ravens",
    "baltimore": "Baltimore Ravens",
    "bills": "Buffalo Bills",
    "buffalo": "Buffalo Bills",
    "panthers": "Carolina Panthers",
    "carolina": "Carolina Panthers",
    "bears": "Chicago Bears",
    "bengals": "Cincinnati Bengals",
    "cincinnati": "Cincinnati Bengals",
    "browns": "Cleveland Browns",
    "cowboys": "Dallas Cowboys",
    "broncos": "Denver Broncos",
    "lions": "Detroit Lions",
    "packers": "Green Bay Packers",
    "green bay": "Green Bay Packers",
    "texans": "Houston Texans",
    "colts": "Indianapolis Colts",
    "indianapolis": "Indianapolis Colts",
    "jaguars": "Jacksonville Jaguars",
    "jags": "Jacksonville Jaguars",
    "jacksonville": "Jacksonville Jaguars",
    "chiefs": "Kansas City Chiefs",
    "kansas city": "Kansas City Chiefs",
    "raiders": "Las Vegas Raiders",
    "las vegas raiders": "Las Vegas Raiders",
    "chargers": "Los Angeles Chargers",
    "la chargers": "Los Angeles Chargers",
    "rams": "Los Angeles Rams",
    "la rams": "Los Angeles Rams",
    "dolphins": "Miami Dolphins",
    "vikings": "Minnesota Vikings",
    "patriots": "New England Patriots",
    "new england": "New England Patriots",
    "pats": "New England Patriots",
    "saints": "New Orleans Saints",
    "giants": "New York Giants",
    "ny giants": "New York Giants",
    "jets": "New York Jets",
    "ny jets": "New York Jets",
    "eagles": "Philadelphia Eagles",
    "steelers": "Pittsburgh Steelers",
    "pittsburgh": "Pittsburgh Steelers",
    "49ers": "San Francisco 49ers",
    "niners": "San Francisco 49ers",
    "san francisco": "San Francisco 49ers",
    "seahawks": "Seattle Seahawks",
    "seattle": "Seattle Seahawks",
    "buccaneers": "Tampa Bay Buccaneers",
    "bucs": "Tampa Bay Buccaneers",
    "tampa bay": "Tampa Bay Buccaneers",
    "titans": "Tennessee Titans",
    "tennessee": "Tennessee Titans",
    "commanders": "Washington Commanders",
}

NHL_ALIASES = {
    "ducks": "Anaheim Ducks",
    "anaheim": "Anaheim Ducks",
    "coyotes": "Arizona Coyotes",
    "utah hockey club": "Utah Hockey Club",
    "bruins": "Boston Bruins",
    "sabres": "Buffalo Sabres",
    "flames": "Calgary Flames",
    "calgary": "Calgary Flames",
    "hurricanes": "Carolina Hurricanes",
    "blackhawks": "Chicago Blackhawks",
    "avalanche": "Colorado Avalanche",
    "colorado": "Colorado Avalanche",
    "blue jackets": "Columbus Blue Jackets",
    "columbus": "Columbus Blue Jackets",
    "stars": "Dallas Stars",
    "red wings": "Detroit Red Wings",
    "oilers": "Edmonton Oilers",
    "edmonton": "Edmonton Oilers",
    "panthers": "Florida Panthers",
    "florida panthers": "Florida Panthers",
    "kings": "Los Angeles Kings",
    "la kings": "Los Angeles Kings",
    "wild": "Minnesota Wild",
    "canadiens": "Montreal Canadiens",
    "habs": "Montreal Canadiens",
    "montreal": "Montreal Canadiens",
    "predators": "Nashville Predators",
    "preds": "Nashville Predators",
    "nashville": "Nashville Predators",
    "devils": "New Jersey Devils",
    "new jersey": "New Jersey Devils",
    "islanders": "New York Islanders",
    "ny islanders": "New York Islanders",
    "rangers": "New York Rangers",
    "ny rangers": "New York Rangers",
    "senators": "Ottawa Senators",
    "ottawa": "Ottawa Senators",
    "flyers": "Philadelphia Flyers",
    "penguins": "Pittsburgh Penguins",
    "sharks": "San Jose Sharks",
    "san jose": "San Jose Sharks",
    "kraken": "Seattle Kraken",
    "blues": "St. Louis Blues",
    "st louis": "St. Louis Blues",
    "lightning": "Tampa Bay Lightning",
    "maple leafs": "Toronto Maple Leafs",
    "leafs": "Toronto Maple Leafs",
    "canucks": "Vancouver Canucks",
    "vancouver": "Vancouver Canucks",
    "golden knights": "Vegas Golden Knights",
    "vegas": "Vegas Golden Knights",
    "capitals": "Washington Capitals",
    "caps": "Washington Capitals",
    "jets": "Winnipeg Jets",
    "winnipeg": "Winnipeg Jets",
}

MLB_ALIASES = {
    "diamondbacks": "Arizona Diamondbacks",
    "d-backs": "Arizona Diamondbacks",
    "braves": "Atlanta Braves",
    "orioles": "Baltimore Orioles",
    "red sox": "Boston Red Sox",
    "cubs": "Chicago Cubs",
    "white sox": "Chicago White Sox",
    "reds": "Cincinnati Reds",
    "guardians": "Cleveland Guardians",
    "rockies": "Colorado Rockies",
    "tigers": "Detroit Tigers",
    "astros": "Houston Astros",
    "royals": "Kansas City Royals",
    "angels": "Los Angeles Angels",
    "la angels": "Los Angeles Angels",
    "dodgers": "Los Angeles Dodgers",
    "la dodgers": "Los Angeles Dodgers",
    "marlins": "Miami Marlins",
    "brewers": "Milwaukee Brewers",
    "twins": "Minnesota Twins",
    "mets": "New York Mets",
    "ny mets": "New York Mets",
    "yankees": "New York Yankees",
    "ny yankees": "New York Yankees",
    "athletics": "Oakland Athletics",
    "a's": "Oakland Athletics",
    "oakland": "Oakland Athletics",
    "phillies": "Philadelphia Phillies",
    "pirates": "Pittsburgh Pirates",
    "padres": "San Diego Padres",
    "san diego": "San Diego Padres",
    "giants": "San Francisco Giants",
    "mariners": "Seattle Mariners",
    "cardinals": "St. Louis Cardinals",
    "st louis cardinals": "St. Louis Cardinals",
    "rays": "Tampa Bay Rays",
    "rangers": "Texas Rangers",
    "texas": "Texas Rangers",
    "blue jays": "Toronto Blue Jays",
    "nationals": "Washington Nationals",
}

SOCCER_ALIASES = {
    # EPL
    "arsenal": "Arsenal FC",
    "arsenal fc": "Arsenal FC",
    "aston villa": "Aston Villa",
    "bournemouth": "AFC Bournemouth",
    "brentford": "Brentford FC",
    "brighton": "Brighton and Hove Albion",
    "burnley": "Burnley FC",
    "chelsea": "Chelsea FC",
    "crystal palace": "Crystal Palace",
    "everton": "Everton FC",
    "fulham": "Fulham FC",
    "ipswich": "Ipswich Town",
    "ipswich town": "Ipswich Town",
    "leicester": "Leicester City",
    "leicester city": "Leicester City",
    "liverpool": "Liverpool FC",
    "luton": "Luton Town",
    "man city": "Manchester City",
    "manchester city": "Manchester City",
    "man united": "Manchester United",
    "man utd": "Manchester United",
    "manchester united": "Manchester United",
    "newcastle": "Newcastle United",
    "newcastle united": "Newcastle United",
    "nottingham forest": "Nottingham Forest",
    "forest": "Nottingham Forest",
    "sheffield united": "Sheffield United",
    "southampton": "Southampton FC",
    "tottenham": "Tottenham Hotspur",
    "spurs": "Tottenham Hotspur",
    "west ham": "West Ham United",
    "west ham united": "West Ham United",
    "wolves": "Wolverhampton Wanderers",
    "wolverhampton": "Wolverhampton Wanderers",
    # La Liga
    "real madrid": "Real Madrid",
    "barcelona": "FC Barcelona",
    "fc barcelona": "FC Barcelona",
    "barca": "FC Barcelona",
    "atletico madrid": "Atletico Madrid",
    "atlético madrid": "Atletico Madrid",
    "atletico": "Atletico Madrid",
    "atlético": "Atletico Madrid",
    "club atlético de madrid": "Atletico Madrid",
    "alavés": "Alaves",
    "deportivo alavés": "Alaves",
    "sevilla": "Sevilla FC",
    "real sociedad": "Real Sociedad",
    "villarreal": "Villarreal CF",
    "real betis": "Real Betis",
    "athletic bilbao": "Athletic Bilbao",
    "athletic club": "Athletic Bilbao",
    "rayo vallecano": "Rayo Vallecano",
    "oviedo": "Oviedo",
    "pisa": "Pisa",
    # Serie A
    "ac milan": "AC Milan",
    "milan": "AC Milan",
    "fc internazionale milano": "Inter Milan",
    "inter milan": "Inter Milan",
    "inter": "Inter Milan",
    "juventus": "Juventus FC",
    "juve": "Juventus FC",
    "napoli": "SSC Napoli",
    "roma": "AS Roma",
    "as roma": "AS Roma",
    "lazio": "SS Lazio",
    "atalanta": "Atalanta BC",
    "fiorentina": "ACF Fiorentina",
    "parma": "Parma",
    "bologna": "Bologna",
    "cagliari": "Cagliari",
    "como": "Como",
    "genoa": "Genoa",
    "sassuolo": "Sassuolo",
    "udinese": "Udinese",
    # Bundesliga
    "bayern munich": "Bayern Munich",
    "bayern": "Bayern Munich",
    "borussia dortmund": "Borussia Dortmund",
    "dortmund": "Borussia Dortmund",
    "bvb": "Borussia Dortmund",
    "rb leipzig": "RB Leipzig",
    "leipzig": "RB Leipzig",
    "bayer leverkusen": "Bayer Leverkusen",
    "leverkusen": "Bayer Leverkusen",
    # Ligue 1
    "psg": "Paris Saint-Germain",
    "paris saint-germain": "Paris Saint-Germain",
    "marseille": "Olympique de Marseille",
    "lyon": "Olympique Lyonnais",
    "monaco": "AS Monaco",
    "lille": "Lille OSC",
    "stade brestois": "Brest",
    "brestois": "Brest",
    "stade rennais": "Rennes",
    "rennais": "Rennes",
    "racing club de lens": "RC Lens",
    "ogc nice": "Nice",
    "metz": "Metz",
    "strasbourg": "Strasbourg",
    # UCL / European additions
    "olympiakós": "Olympiakos Piraeus",
    "fc københavn": "FC Copenhagen",
    "københavn": "FC Copenhagen",
    "qairat": "FC Kairat",
    "benfica": "SL Benfica",
    "porto": "FC Porto",
    "sporting cp": "Sporting CP",
    "ajax": "AFC Ajax",
    "psv": "PSV Eindhoven",
    "celtic": "Celtic FC",
    "galatasaray": "Galatasaray SK",
    # MLS
    "la galaxy": "LA Galaxy",
    "galaxy": "LA Galaxy",
    "lafc": "Los Angeles FC",
    "inter miami": "Inter Miami CF",
    "atlanta united": "Atlanta United FC",
    "nycfc": "New York City FC",
    "new york city fc": "New York City FC",
    "ny red bulls": "New York Red Bulls",
    "new york red bulls": "New York Red Bulls",
    "seattle sounders": "Seattle Sounders FC",
    "sounders": "Seattle Sounders FC",
    "portland timbers": "Portland Timbers",
    "timbers": "Portland Timbers",
}

# Sport -> alias dict mapping
TEAM_ALIASES = {
    "NBA": NBA_ALIASES,
    "NFL": NFL_ALIASES,
    "NHL": NHL_ALIASES,
    "MLB": MLB_ALIASES,
    "Tennis": {},  # Tennis uses player names, not team aliases
    "Soccer": SOCCER_ALIASES,
}

# --- Question-parsing regex patterns ---
# Pattern: "Will <TeamA> beat <TeamB> [on/in] <Date>?"
# Captures various question formats on Polymarket

QUESTION_PATTERNS = [
    # "Will the Lakers beat the Celtics on January 15?"
    re.compile(
        r"(?:Will|Can)\s+(?:the\s+)?(.+?)\s+(?:beat|defeat|win\s+against|win\s+vs\.?)\s+(?:the\s+)?(.+?)(?:\s+on\s+(.+?))?(?:\?|$)",
        re.IGNORECASE,
    ),
    # "Lakers vs. Celtics (Jan 15)" or "Lakers vs Celtics - January 15, 2025"
    re.compile(
        r"(.+?)\s+vs\.?\s+(.+?)(?:\s*[\(\-]\s*(.+?)[\)\s]*)?(?:\?|$)",
        re.IGNORECASE,
    ),
    # "Team A to beat Team B"
    re.compile(
        r"(.+?)\s+to\s+(?:beat|defeat|win\s+against)\s+(.+?)(?:\s+on\s+(.+?))?(?:\?|$)",
        re.IGNORECASE,
    ),
]

# Date patterns in question text
DATE_PATTERNS = [
    # "January 15, 2025" or "Jan 15, 2025"
    re.compile(
        r"((?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z]*\.?\s+\d{1,2},?\s*\d{4})",
        re.IGNORECASE,
    ),
    # "1/15/2025" or "01/15/2025"
    re.compile(r"(\d{1,2}/\d{1,2}/\d{4})"),
    # "2025-01-15"
    re.compile(r"(\d{4}-\d{2}-\d{2})"),
]

# Keywords that indicate non-moneyline markets (spreads, totals, props)
SPREAD_TOTAL_KEYWORDS = [
    "by more than", "over/under", "over ", "under ",
    "total", "points", "spread", "handicap",
    "margin", "score", "goals", "runs",
    "first half", "second half", "quarter",
    "mvp", "most valuable", "award",
    "champion", "win the", "win the series",
    "playoff", "make the playoffs",
]
